### ISSUE TITLE
ActionController::RoutingError (uninitialized constant CustomRelationsFieldsController)

### ISSUE THREAD

**Issue by xaionaro** [kressh/redmine_issues_custom_relations#2]
Hello, can you give an advice how to bypass this error?

```
ActionController::RoutingError (uninitialized constant CustomRelationsFieldsController):
  activesupport (4.1.6) lib/active_support/inflector/methods.rb:238:in `const_get'
  activesupport (4.1.6) lib/active_support/inflector/methods.rb:238:in `block in constantize'
  activesupport (4.1.6) lib/active_support/inflector/methods.rb:236:in `each'
  activesupport (4.1.6) lib/active_support/inflector/methods.rb:236:in `inject'
  activesupport (4.1.6) lib/active_support/inflector/methods.rb:236:in `constantize'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:78:in `controller_reference'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:68:in `controller'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:46:in `call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.6) lib/rails/engine.rb:514:in `call'
  railties (4.1.6) lib/rails/application.rb:144:in `call'
  railties (4.1.6) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.6) lib/rails/railtie.rb:194:in `method_missing'
  public/dispatch.fcgi:16:in `call'
  rack (1.5.2) lib/rack/handler/fastcgi.rb:66:in `serve'
  rack (1.5.2) lib/rack/handler/fastcgi.rb:28:in `block in run'
  /usr/lib/ruby/vendor_ruby/fcgi.rb:122:in `session'
  /usr/lib/ruby/vendor_ruby/fcgi.rb:109:in `each_request'
  /usr/lib/ruby/vendor_ruby/fcgi.rb:41:in `each'
  rack (1.5.2) lib/rack/handler/fastcgi.rb:27:in `run'
  public/dispatch.fcgi:20:in `<main>'
```

**Comment by xaionaro** [comment]
May it be caused by migration problems?

```
# rake redmine:plugins:migrate RAILS_ENV=development
/usr/share/redmine/app/models/query.rb:138: warning: already initialized constant Query::VISIBILITY_PRIVATE
/usr/share/redmine/app/models/query.rb:138: warning: previous definition of VISIBILITY_PRIVATE was here
/usr/share/redmine/app/models/query.rb:139: warning: already initialized constant Query::VISIBILITY_ROLES
/usr/share/redmine/app/models/query.rb:139: warning: previous definition of VISIBILITY_ROLES was here
/usr/share/redmine/app/models/query.rb:140: warning: already initialized constant Query::VISIBILITY_PUBLIC
/usr/share/redmine/app/models/query.rb:140: warning: previous definition of VISIBILITY_PUBLIC was here
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations.rb:1585: warning: already initialized constant Query::HABTM_Roles
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_Roles was here
Migrating issues_custom_relations (Issues Custom Relations plugin)...
```

**Comment by xaionaro** [comment]
The problem was caused by plugin name. However new problem appeared. I'll create another issue.

```
d[21:36:59] [root@anubis:redmine-test /usr/share/redmine/plugins]# mv redmine_issues_custom_relations issues_custom_relations
d[21:37:03] [root@anubis:redmine-test /usr/share/redmine/plugins]# cd ..
d[21:37:04] [root@anubis:redmine-test /usr/share/redmine]# rake redmine:plugins:migrate RAILS_ENV=development
/usr/share/redmine/app/models/query.rb:138: warning: already initialized constant Query::VISIBILITY_PRIVATE
/usr/share/redmine/app/models/query.rb:138: warning: previous definition of VISIBILITY_PRIVATE was here
/usr/share/redmine/app/models/query.rb:139: warning: already initialized constant Query::VISIBILITY_ROLES
/usr/share/redmine/app/models/query.rb:139: warning: previous definition of VISIBILITY_ROLES was here
/usr/share/redmine/app/models/query.rb:140: warning: already initialized constant Query::VISIBILITY_PUBLIC
/usr/share/redmine/app/models/query.rb:140: warning: previous definition of VISIBILITY_PUBLIC was here
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations.rb:1585: warning: already initialized constant Query::HABTM_Roles
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_Roles was here
Migrating issues_custom_relations (Issues Custom Relations plugin)...
== 20140409143941 CreateCustomRelationsFields: migrating ======================
-- create_table(:custom_relations_fields)
   -> 0.1830s
-- add_index(:custom_relations_fields, :custom_field_id)
   -> 0.1111s
-- add_index(:custom_relations_fields, :project_id)
   -> 0.1158s
== 20140409143941 CreateCustomRelationsFields: migrated (0.4102s) =============

== 20140409143942 CreateCustomRelationsValues: migrating ======================
-- create_table(:custom_relations_values)
   -> 0.2029s
-- add_index(:custom_relations_values, :issue_id)
   -> 0.1116s
-- add_index(:custom_relations_values, :custom_relations_field_id)
   -> 0.1119s
-- add_index(:custom_relations_values, :related_issue_id)
   -> 0.1161s
== 20140409143942 CreateCustomRelationsValues: migrated (0.5428s) =============

== 20140409143943 RenameCustomRelationsValuesColumnRelatedIssueId: migrating ==
-- rename_column(:custom_relations_values, :related_issue_id, :issue_to_id)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX `index_custom_relations_values_on_related_issue_id` TO `index_custom_relat' at line 1: ALTER TABLE `custom_relations_values` RENAME INDEX `index_custom_relations_values_on_related_issue_id` TO `index_custom_relations_values_on_issue_to_id`/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/lib/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:493:in `rename_index'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:842:in `block in rename_column_indexes'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `rename_column_indexes'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:520:in `rename_column'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:649:in `block in method_missing'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:621:in `block in say_with_time'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:621:in `say_with_time'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:641:in `method_missing'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:595:in `exec_migration'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:578:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:577:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:752:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:991:in `block in execute_migration_in_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:1039:in `ddl_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:990:in `execute_migration_in_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:952:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:948:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:948:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:807:in `up'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:785:in `migrate'
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX `index_custom_relations_values_on_related_issue_id` TO `index_custom_relat' at line 1: ALTER TABLE `custom_relations_values` RENAME INDEX `index_custom_relations_values_on_related_issue_id` TO `index_custom_relations_values_on_issue_to_id`
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/lib/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:493:in `rename_index'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:842:in `block in rename_column_indexes'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `rename_column_indexes'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:520:in `rename_column'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:649:in `block in method_missing'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:621:in `block in say_with_time'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:621:in `say_with_time'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:641:in `method_missing'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:595:in `exec_migration'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:578:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:577:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:752:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:991:in `block in execute_migration_in_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:1039:in `ddl_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:990:in `execute_migration_in_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:952:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:948:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:948:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:807:in `up'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:785:in `migrate'
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX `index_custom_relations_values_on_related_issue_id` TO `index_custom_relat' at line 1
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/lib/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:493:in `rename_index'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:842:in `block in rename_column_indexes'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `rename_column_indexes'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:520:in `rename_column'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:649:in `block in method_missing'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:621:in `block in say_with_time'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:621:in `say_with_time'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:641:in `method_missing'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:595:in `exec_migration'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:578:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:577:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:752:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:991:in `block in execute_migration_in_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:1039:in `ddl_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:990:in `execute_migration_in_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:952:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:948:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:948:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:807:in `up'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:785:in `migrate'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by bsedin** [comment]
Hello! @xaionaro, did you solve problem?

**Comment by xaionaro** [comment]
Well, I faced 4 problems and solved 2 of them:

`1`. uninitialized constant CustomRelationsFieldsController

It's just required to rename plugin dir from "redmine_issues_custom_relations" to "issues_custom_relations" (in redmine/plugins).

`2`. "RENAME INDEX" SQL syntax error.

The problem caused by MySQL version. RENAME INDEX appeared only on 5.7 [1].

[1] http://stackoverflow.com/questions/1463363/how-do-i-rename-an-index-in-mysql

It's just required to remove a column rename from "db/migrate" [2]. I updated the column name in 20140409143942_create_custom_relations_values to compensate the change.

[2] http://stackoverflow.com/questions/27443178/rails-4-rename-column-gets-mysql-syntax-error

`3`. I need to apply a relation to all of my 4000 projects. But the plugin allows to create a relation for a one project-pair.

`4`. I got error while trying to create a relation (see the screenshot below).
![screenshot from 2015-12-10 21 54 44](https://cloud.githubusercontent.com/assets/2349376/11725056/b4f03d54-9f88-11e5-8a6b-d2e516c58745.png)

May be problems 3 and 4 are not real problems but just my stupidness, but I'm too lazy to try to solve them :)

**Comment by bsedin** [comment]
1. I remember that problem, that's why in readme I specify destination directory for `git clone`. This is not obvious, I'll add warning later.
2. You right, this plugin provides one to one relation for projects. I guess you can patch this to be habtm.
3. I'll check it right now

**Comment by xaionaro** [comment]
> I'll check it right now

Actually, I have very custom Redmine. This may be caused by my modifications. Don't waste your time on that :)

**Comment by bsedin** [comment]
So, I've checked and fixed problem with permitted params.
Thank you for being active in such a necrorepository!
